Repository simonskodt/itu-minitwit, pull requests merged in 2023-02, with the labels that each got.

#14 Final setup for repository and controller layers
  MiniTwit.Core/IRepositories/IMongoDBRepository.cs
  MiniTwit.Infrastructure/Repositories/MongoDBRepository.cs
  MiniTwit.Server/Controllers/TwitterController.cs
  MiniTwit.Web/src/pages/Login.tsx
Labels: enhancement

#15 Improve endpoints
  MiniTwit.Core/Entities/Follower.cs
  MiniTwit.Core/Entities/User.cs
  MiniTwit.Core/IRepositories/IMongoDBRepository.cs
  MiniTwit.Core/MiniTwit.Core.csproj
  MiniTwit.Infrastructure/MiniTwit.Infrastructure.csproj
  MiniTwit.Infrastructure/Repositories/MongoDBRepository.cs
  MiniTwit.Server/Controllers/TwitterController.cs
  MiniTwit.Server/MiniTwit.Server.csproj
  MiniTwit.Server/MinitwitDatabaseSettings.cs
Labels: enhancement

#16 feat: MongoDB now loads configuration from secrets and container
  .gitignore
  MiniTwit.Core/IMongoDBContext.cs
  MiniTwit.Core/MiniTwitDatabaseSettings.cs
  MiniTwit.Infrastructure/MongoDBContext.cs
  MiniTwit.Server/MiniTwit.Server.csproj
  MiniTwit.Server/Program.cs
  MiniTwit.Server/appsettings.Development.json
  docker-compose.yml
  run.sh
Labels: enhancement

#17 feat(components): add various components for front-end
  MiniTwit.Infrastructure/Repositories/MongoDBRepository.cs
  MiniTwit.Web/src/App.css
  MiniTwit.Web/src/index.css
  MiniTwit.Web/src/pages/Footer.tsx
  MiniTwit.Web/src/pages/Layout.css
  MiniTwit.Web/src/pages/Layout.tsx
  MiniTwit.Web/src/pages/Login.tsx
  MiniTwit.Web/src/pages/Menu.tsx
  MiniTwit.Web/src/pages/TimeLine.tsx
Labels: help wanted

#21 feat(components): create message and header
  MiniTwit.Web/src/pages/Footer.tsx
  MiniTwit.Web/src/pages/Header.tsx
  MiniTwit.Web/src/pages/Layout.tsx
  MiniTwit.Web/src/pages/Menu.tsx
  MiniTwit.Web/src/pages/Message.tsx
  MiniTwit.Web/src/pages/PublicTimeline.tsx
  MiniTwit.Web/src/pages/TimeLine.tsx
  MiniTwit.Web/src/pages/fetch.ts
Labels: enhancement

#28 feat(latest): Implemented initial version of /sim
  MiniTwit.Core/Entities/Follower.cs
  MiniTwit.Core/Entities/Latest.cs
  MiniTwit.Core/IMongoDBContext.cs
  MiniTwit.Core/IRepositories/IFollowerRepository.cs
  MiniTwit.Core/IRepositories/ILatestRepository.cs
  MiniTwit.Core/MiniTwitDatabaseSettings.cs
  MiniTwit.Infrastructure/Data/DataCreators/LatestCreator.cs
  MiniTwit.Infrastructure/Data/DataInitializer.cs
  MiniTwit.Infrastructure/MongoDBContext.cs
  MiniTwit.Infrastructure/Repositories/FollowerRepository.cs
  MiniTwit.Infrastructure/Repositories/LatestRepository.cs
  MiniTwit.Infrastructure/Repositories/MessageRepository.cs
  MiniTwit.Server/Controllers/SimController.cs
  MiniTwit.Server/Program.cs
  MiniTwit.Server/appsettings.json
Labels: enhancement

#31 feat(SimController): Finished Simcontroller endpoints
  MiniTwit.Core/DTOs/LoginDTO.cs
  MiniTwit.Core/DTOs/RegisterDTO.cs
  MiniTwit.Core/DTOs/SimFollowDTO.cs
  MiniTwit.Server/Controllers/SimController.cs
Labels: enhancement

#43 Fix front end
  MiniTwit.Web/Dockerfile
  MiniTwit.Web/src/App.tsx
  MiniTwit.Web/src/pages/Header.tsx
  MiniTwit.Web/src/pages/Login.tsx
  MiniTwit.Web/src/pages/PublicTimeline.tsx
  MiniTwit.Web/src/pages/TimeLine.tsx
  MiniTwit.Web/src/pages/fetch.ts
  MiniTwit.Web/src/services/app.service.ts
  docker-compose.yml
Labels: bug
